# Generated by Django 2.1 on 2019-07-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_remove_book_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=20, unique=True)),
                ('book_issued', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
