# Generated by Django 2.1 on 2019-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='costprice',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=252, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
