# Generated by Django 2.1 on 2019-09-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_user_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book_issued',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
