# Generated by Django 2.1 on 2019-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190924_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
