# Generated by Django 2.1 on 2019-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20190924_1855'),
        ('issues', '0003_auto_20190924_1643'),
    ]

    operations = [
    ]
